# Generated by Django 2.2.4 on 2025-04-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20250418_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='pie',
            name='crust',
            field=models.CharField(default='Vanilla', max_length=25),
        ),
        migrations.AddField(
            model_name='pie',
            name='filling',
            field=models.CharField(default='Cheese', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='2025-04-21', max_length=45),
            preserve_default=False,
        ),
    ]
