# Generated by Django 2.2.4 on 2025-04-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20250421_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='Qwer@1234', max_length=45),
            preserve_default=False,
        ),
    ]
