# Generated by Django 2.2.4 on 2025-04-21 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20250421_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='pie',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mypie', to='mainapp.User'),
        ),
    ]
